repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.76.0 # Get the latest from: https://github.com/antonbabenko/pre-commit-terraform/releases
    hooks:
      # Code formatting and linting
      - id: terraform_fmt
        args:
          - --args=-no-color
          - --args=-diff
          # - --args=-check
          # - --args=-recursive
          - --args=-write=false
      - id: terraform_tflint
        args:
          - --args=--module
          - --args=--enable-rule=terraform_documented_variables

      # Auto-documentation 
      - id: terraform_docs
        args:
          - --hook-config=--path-to-file=README.md # Valid UNIX path. I.e. ../TFDOC.md or docs/README.md etc.
          - --hook-config=--add-to-existing-file=true # Boolean. true or false
          - --hook-config=--create-file-if-not-exist=true # Boolean. true or false

      # Security scans
      - id: terraform_checkov
        args:
          - --args=--quiet
      # - id: terraform_tfsec